<?php

namespace CimpleAdmin\Forms\Builder;

use CimpleAdmin\Forms\Builder\Traits\HasOptions;
use CimpleAdmin\Forms\Builder\Traits\HasRuleItemInArray;
use CimpleAdmin\Forms\Builder\Traits\HasRuleItemInOptions;

class CheckList extends Component
{
    use HasOptions;
    use HasRuleItemInArray;
    use HasRuleItemInOptions;

    const COMPONENT_NAME = 'checkbox';

    public function __construct($property)
    {
        parent::__construct($property);
        $this->rules['value'][] = 'array';
        $this->value = [];
    }

    public function build(): array
    {
        $params = parent::build(); // TODO: Change the autogenerated stub
        $params['options'] = $this->options;

        return $params;
    }
}
