<?php

namespace CimpleAdmin\Forms\Builder;

use CimpleAdmin\Forms\Builder\Traits\HasOptions;
use CimpleAdmin\Forms\Builder\Traits\HasRuleItemInArray;
use CimpleAdmin\Forms\Builder\Traits\HasRuleItemInOptions;
use Illuminate\Validation\Rule;

class Radio extends Component
{
    use HasOptions;
//    use HasRuleItemInArray;
//    use HasRuleItemInOptions;

    const COMPONENT_NAME = 'radio';

    public function itemInArray($options): static
    {
        $this->rules['value'][] = Rule::in($options);

        return $this;
    }

    public function itemInOption(): static
    {
        $this->rules['value'][] = Rule::in(array_keys($this->options));

        return $this;
    }

    public function build(): array
    {
        $params = parent::build(); // TODO: Change the autogenerated stub
        $params['options'] = $this->options;

        return $params;
    }
}
