<?php

namespace CimpleAdmin\Forms\Builder;

class TextInput extends Component
{
    const COMPONENT_NAME = 'input-text';
    public string $type = 'text';

    public function type($type): static
    {
        $this->type = $type;

        return $this;
    }

    public function build(): array
    {
        $params =  parent::build(); // TODO: Change the autogenerated stub
        $params['type'] = $this->type;
        return $params;
    }
}
