<?php

namespace CimpleAdmin\Forms\Traits;

use CimpleAdmin\Forms\Components\Container;
use Livewire\Exceptions\PropertyNotFoundException;

trait HasFormTrait
{
    public function __get($property)
    {
        try {
            return parent::__get($property);
        } catch (PropertyNotFoundException $e) {
            return Container::make($this->getForm());
        } // TODO: Change the autogenerated stub
    }
}